Django_level_four/Learning_templates/Learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^basic_app/', include('basic_app.urls'))
]

Django_level_four/Learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

#TEMPLATE TAGGINGS
app_name="basic_app"

urlpatterns = [
    url(r'^relative/$', views.relative, name='relative'),
    url(r'^other/$', views.other, name='other'),
]

Django_level_four/Learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

Django_level_four/Learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'basic_app/index.html')

def other(request):
    return render(request, 'basic_app/other.html')

def relative(request):
    return render(request, 'basic_app/relative.html')

Django_level_four/Learning_templates/templates/basic_app/basic.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  <head>
    <meta charset="utf-8">
    <title>Basic</title>
  </head>
  <body>
      <nav class= "navbar navbar-toggleable-md navbar-light bg-faded">
        <div class="container">
          <ul class="nav navbar-nav">
            <li class="nav-item"><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'basic_app:other' %}">Other</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'basic_app:relative' %}">Relative</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
          </ul>
        </div>
      </nav>
      <br>
      <div class="container">
        {% block body_block %}
        <!-- Code -->
        {% endblock %}
      </div>
  </body>
</html>

Django_level_four/Learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/basic.html" %}
  {% block body_block %}
  <h1>Welcome to index page!</h1>
  {% endblock %}

Django_level_four/Learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/basic.html" %}
  {% block body_block %}
  <h1>Welcome to other page!</h1>
  {% endblock %}

Django_level_four/Learning_templates/templates/basic_app/relative.html
<!DOCTYPE html>
{% extends "basic_app/basic.html" %}
  {% block body_block %}
  <h1>Welcome to relative page!</h1>
  {% endblock %}